### ISSUE TITLE
Migrating AccountAction saveAccount using Adapter

### ISSUE THREAD

**Issue by reehanlalkhan** [musaibasrar/Curium#160]
#### Task Description
* Migrating AccountAction saveAccount using Adapter
* Steps needed to complete the task
- [x] Create the adapter
- [x] Make saveAccount call the Adapter
- [x] Make the Adapter call the service
- [x] Make changes in service to receive the parameter from Adapter
