### ISSUE TITLE
Remove request response from Student creation request

### ISSUE THREAD

**Issue by reehanlalkhan** [musaibasrar/Curium#84]
#### Task Description
* Create StudentDto to capture the data from the elements
* Add model attribute to the JSP to capture data in DTO
* Remove request response from add-student
- [ ] Capture StudentDto as ModelAttribute in Action
- [ ] Pass the DTO to StudentService
- [ ] Create mapper to copy data from dto to Model class
- [ ] Save the model class

#### Code Example
```
public String addStudent(@ModelAttribute("student") StudentDto student
```
